/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.brapi.v2.api;

import io.swagger.annotations.*;

import org.brapi.v2.model.CallListResponse;
import org.brapi.v2.model.CallSetResponse1;
import org.brapi.v2.model.VariantListResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-19T12:30:12.318Z[GMT]")
@Api(value = "variants", description = "the variants API")
public interface VariantsApi {

    @ApiOperation(value = "Gets a filtered list of `Variants`.", nickname = "variantsGet", notes = "`GET /variants` will return a filtered list of `Variants`.", response = VariantListResponse.class, authorizations = {
        @Authorization(value = "AuthorizationToken")    }, tags={ "Variants", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A successful response.", response = VariantListResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = String.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
        @ApiResponse(code = 403, message = "Forbidden", response = String.class) })
    @RequestMapping(value = CallsApi.URL_BASE_PREFIX + "/variants",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<VariantListResponse> variantsGet(@ApiParam(value = "The ID of the `Variant` to be retrieved.") @Valid @RequestParam(value = "variantDbId", required = false) String variantDbId,@ApiParam(value = "The ID of the `VariantSet` to be retrieved.") @Valid @RequestParam(value = "variantSetDbId", required = false) String variantSetDbId,@ApiParam(value = "Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "The size of the pages to be returned. Default is `1000`.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>" ) @RequestHeader(value="Authorization", required=false) String authorization);


    @ApiOperation(value = "Gets a list of `Calls` associated with a `Variant`.", nickname = "variantsVariantDbIdCallsGet", notes = " The variant calls for this particular variant. Each one represents the determination of genotype with respect to this variant. `Call`s in this array are implicitly associated with this `Variant`. Also See: `GET /calls?variantDbId={variantDbId}` ", response = CallListResponse.class, authorizations = {
        @Authorization(value = "AuthorizationToken")    }, tags={ "Variants", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CallListResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = String.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
        @ApiResponse(code = 403, message = "Forbidden", response = String.class) })
    @RequestMapping(value = CallsApi.URL_BASE_PREFIX + "/variants/{variantDbId}/calls",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CallListResponse> variantsVariantDbIdCallsGet(@ApiParam(value = "The ID of the `Variant` to be retrieved.",required=true) @PathVariable("variantDbId") String variantDbId,@ApiParam(value = "Should homozygotes be expanded (true) or collapsed into a single occurence (false)") @Valid @RequestParam(value = "expandHomozygotes", required = false) Boolean expandHomozygotes,@ApiParam(value = "The string to use as a representation for missing data") @Valid @RequestParam(value = "unknownString", required = false) String unknownString,@ApiParam(value = "The string to use as a separator for phased allele calls") @Valid @RequestParam(value = "sepPhased", required = false) String sepPhased,@ApiParam(value = "The string to use as a separator for unphased allele calls") @Valid @RequestParam(value = "sepUnphased", required = false) String sepUnphased,@ApiParam(value = "Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "The size of the pages to be returned. Default is `1000`.") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>" ) @RequestHeader(value="Authorization", required=false) String authorization);


    @ApiOperation(value = "Gets a `Variant` by ID.", nickname = "variantsVariantDbIdGet", notes = "`GET /variants/{id}` will return a JSON version of `Variant`.", response = CallSetResponse1.class, authorizations = {
        @Authorization(value = "AuthorizationToken")    }, tags={ "Variants", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CallSetResponse1.class),
        @ApiResponse(code = 400, message = "Bad Request", response = String.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
        @ApiResponse(code = 403, message = "Forbidden", response = String.class),
        @ApiResponse(code = 404, message = "Not Found", response = String.class) })
    @RequestMapping(value = CallsApi.URL_BASE_PREFIX + "/variants/{variantDbId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CallSetResponse1> variantsVariantDbIdGet(@ApiParam(value = "The ID of the `Variant` to be retrieved.",required=true) @PathVariable("variantDbId") String variantDbId,@ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>" ) @RequestHeader(value="Authorization", required=false) String authorization);

}
