/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.brapi.v2.api;

import java.io.UnsupportedEncodingException;
import java.net.SocketException;
import java.net.UnknownHostException;

import javax.validation.Valid;

import org.brapi.v2.model.CallListResponse;
import org.brapi.v2.model.CallsSearchRequest;
import org.brapi.v2.model.SuccessfulSearchResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import org.brapi.v2.model.VariantMatrixResponse;
import org.brapi.v2.model.VariantMatrixSearchRequest;

@Api(value = "variantMatrix", description = "the variantMatrix API", tags={ "VariantMatrix" })
public interface VariantMatrixApi {

    public static final String variantMatrixGet_url = "calls";
    public static final String searchVariantMatrixPost_url = "search/variantMatrix";
    
	@ApiOperation(value = "Returns a filtered list of `Calls`", notes = "Returns a filtered list of `Call` objects. At least one callSetDbId, variantDbId or variantSetDbId must be specified.  ** THIS ENDPOINT USES TOKEN BASED PAGING **", authorizations = {
			@Authorization(value = "AuthorizationToken")    }, tags={ "Calls" })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CallListResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = String.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
        @ApiResponse(code = 403, message = "Forbidden", response = String.class) })
	
    @RequestMapping(value = ServerinfoApi.URL_BASE_PREFIX + "/" + variantMatrixGet_url, produces = { "application/json" }, method = RequestMethod.GET) ResponseEntity<VariantMatrixResponse> variantMatrixGet(
                @ApiParam(value = "The requested page number for the Variant dimension of the matrix") @Valid @RequestParam(value = "dimensionVariantPage", required = false) Integer dimensionVariantPage,
                @ApiParam(value = "The requested page size for the Variant dimension of the matrix") @Valid @RequestParam(value = "dimensionVariantPageSize", required = false) Integer dimensionVariantPageSize,
                @ApiParam(value = "The requested page number for the CallSet dimension of the matrix") @Valid @RequestParam(value = "dimensionCallSetPage", required = false) Integer dimensionCallSetPage,
                @ApiParam(value = "The requested page size for the CallSet dimension of the matrix") @Valid @RequestParam(value = "dimensionCallSetPageSize", required = false) Integer dimensionCallSetPageSize,
                @ApiParam(value = "The postion range to search") @Valid @RequestParam(value = "positionRange", required = false) String positionRange,
            
                @ApiParam(value = "Internal database identifier of germplasm") @Valid @RequestParam(value = "germplasmDbId", required = false) String germplasmDbId,
                @ApiParam(value = "Name of the germplasm") @Valid @RequestParam(value = "germplasmName", required = false) String germplasmName,
                @ApiParam(value = "Permanent unique identifier (DOI, URI, etc.)") @Valid @RequestParam(value = "germplasmPUI", required = false) String germplasmPUI,
    		@ApiParam(value = "The ID of the `CallSet` to be retrieved.") @Valid @RequestParam(value = "callSetDbId", required = false) String callSetDbId,
    		@ApiParam(value = "The ID of the `Variant` to be retrieved.") @Valid @RequestParam(value = "variantDbId", required = false) String variantDbId,
    		@ApiParam(value = "The ID of the `VariantSet` to be retrieved.") @Valid @RequestParam(value = "variantSetDbId", required = false) String variantSetDbId,
                
    		@ApiParam(value = "Should homozygotes be expanded (true) or collapsed into a single occurrence (false)") @Valid @RequestParam(value = "expandHomozygotes", required = false) Boolean expandHomozygotes,
    		@ApiParam(value = "The string to use as a representation for missing data") @Valid @RequestParam(value = "unknownString", required = false) String unknownString,
    		@ApiParam(value = "The string to use as a separator for phased allele calls") @Valid @RequestParam(value = "sepPhased", required = false) String sepPhased,
    		@ApiParam(value = "The string to use as a separator for unphased allele calls") @Valid @RequestParam(value = "sepUnphased", required = false) String sepUnphased,
    		@ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value="Authorization", required=false) String authorization) throws SocketException, UnknownHostException, UnsupportedEncodingException;
	
    @ApiOperation(value = "Returns a filtered list of `Call` objects", nickname = "searchCallsPost", notes = "Returns a filtered list of `Call` objects. At least one callSetDbId, variantDbId or variantSetDbId must be specified.  ** THIS ENDPOINT USES TOKEN BASED PAGING **", response = SuccessfulSearchResponse.class, authorizations = {
	        @Authorization(value = "AuthorizationToken")    }, tags={ "Calls" })
	    @ApiResponses(value = { 
	        @ApiResponse(code = 200, message = "OK", response = SuccessfulSearchResponse.class),
	        @ApiResponse(code = 400, message = "Bad Request", response = String.class),
	        @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
	        @ApiResponse(code = 403, message = "Forbidden", response = String.class) })
	    @RequestMapping(value = ServerinfoApi.URL_BASE_PREFIX + "/" + searchVariantMatrixPost_url,
	        produces = { "application/json" }, 
	        consumes = { "application/json" },
	        method = RequestMethod.POST)
	    ResponseEntity<VariantMatrixResponse> searchVariantMatrixPost(@ApiParam @Valid @RequestBody VariantMatrixSearchRequest body, @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>" ) @RequestHeader(value="Authorization", required=false) String authorization) throws SocketException, UnknownHostException, UnsupportedEncodingException;

	
}